apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-advanced-tooling
    
deploy:
  helm:
    releases:
      - name: eoap-advanced-tooling
        chartPath: ../charts/coder
        namespace: eoap-advanced-tooling
        createNamespace: true
        setValues:
          coder.coderImage: eoepca/pde-code-server:1.0.0
          coder.workspace: advanced-tooling
          coderstorageClassName: standard
          coder.workspaceStorage: 10Gi
          coderResources.limits.cpu: '2'
          coderResources.limits.memory: '6442450944'
          coderResources.requests.cpu: '1'
          coderResources.requests.memory: '4294967296'
          coder.securityContext.privileged: false
          calrissian.enabled: true
          skaffold.enabled: true
          
        setFiles: {
          initScript: ./files/init.sh,
          bashrcScript: ./files/bash-rc,
          bashloginScript: ./files/bash-login
        }
      - name: eoap-advanced-tooling-localstack
        remoteChart: localstack/localstack
        namespace: eoap-advanced-tooling
        createNamespace: true
        setValues:
          service.type: ClusterIP

portForward:
  - resourceType: service
    resourceName: code-server-service
    namespace: eoap-advanced-tooling 
    address: localhost
    port: 8080
    localPort: 8000