{{ if .Values.calrissian.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calrissian-sa
{{- if .Values.calrissian.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.calrissian.imagePullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}

{{ end }}
