
coder:
  coderImage: eoepca/pde-code-server:1.0.0
  workspace: quickwin
  storageClassName: standard
  workspaceStorage: 20Gi
  securityContext:
    privileged: true

calrissian:
  enabled: True
  storage: 10Gi
  storageClassName: standard
  imagePullSecrets:
    - kaniko-secret

coderResources:
  limits:
    cpu: '2'
    memory: '6442450944'
  requests:
    cpu: '1'
    memory: '4294967296'

skaffold:
  enabled: False